name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta diariamente a medianoche UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generar la animación
        uses: Platane/snk@v3
        with:
          github_user_name: MiguelAndresGuerrero
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir la animación al repositorio
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
